/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#68fcbf",
        "on-error": "#ffffff",
        "outline": "#6c7a71",
        "background": "#f4fbf7",
        "surface-bright": "#f4fbf7",
        "tertiary-fixed-dim": "#ffb3af",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "tertiary": "#a43a3a",
        "primary-fixed-dim": "#4edea3",
        "surface-tint": "#006c49",
        "outline-variant": "#bbcabf",
        "on-surface": "#131e19",
        "on-primary-fixed-variant": "#005236",
        "on-primary-container": "#00422b",
        "on-background": "#131e19",
        "secondary-fixed-dim": "#45dfa4",
        "inverse-surface": "#27332d",
        "surface-container": "#e4f1e8",
        "surface-container-high": "#deebe3",
        "on-secondary": "#ffffff",
        "surface-dim": "#d0ddd5",
        "primary-container": "#10b981",
        "on-tertiary-fixed-variant": "#842225",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eaf7ee",
        "tertiary-fixed": "#ffdad7",
        "tertiary-container": "#fc7c78",
        "secondary": "#006c4b",
        "on-secondary-fixed-variant": "#005137",
        "on-secondary-fixed": "#002114",
        "secondary-container": "#64f9bc",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#e7f4eb",
        "surface-variant": "#d9e6dd",
        "on-tertiary-fixed": "#410005",
        "on-surface-variant": "#3c4a42",
        "error": "#ba1a1a",
        "surface-container-highest": "#d9e6dd",
        "surface": "#f4fbf7",
        "on-tertiary-container": "#711419",
        "inverse-primary": "#4edea3",
        "primary-fixed": "#6ffbbe",
        "on-secondary-container": "#00714e",
        "primary": "#006c49",
        "on-primary-fixed": "#002113",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ['"Plus Jakarta Sans"', "sans-serif"],
        label: ['"Plus Jakarta Sans"', "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
